# Generated by Django 5.2.9 on 2026-01-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='winner_notified',
            field=models.BooleanField(default=False),
        ),
    ]
