# Generated by Django 5.2.6 on 2026-01-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = []
