# Generated by Django 5.2.6 on 2026-01-13 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_bid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='bid_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('starting_price__gte', 0)), name='item_starting_price_gte_0'),
        ),
    ]
