# Generated by Django 5.2.6 on 2026-01-20 12:41

import api.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_date_of_birth_user_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=api.storage.PrivateMediaStorage(), upload_to='profile_images/'),
        ),
    ]
