# Generated by Django 3.2 on 2026-01-19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_bid_bid_amount_gt_0_item_item_starting_price_gte_0"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image_url", models.URLField()),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="api.item"),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="itemimage",
            constraint=models.UniqueConstraint(fields=("item", "position"), name="item_image_unique_position"),
        ),
    ]
