# Generated by GitHub Copilot on 2026-01-21

from django.db import migrations


def add_image_url_column(apps, schema_editor):
    Item = apps.get_model("api", "Item")
    table = Item._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        columns = [
            column.name
            for column in schema_editor.connection.introspection.get_table_description(cursor, table)
        ]
    if "image_url" in columns:
        return
    field = Item._meta.get_field("image_url")
    schema_editor.add_field(Item, field)


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_bid_bid_amount_gt_0_item_item_starting_price_gte_0"),
    ]

    operations = [
        migrations.RunPython(add_image_url_column, migrations.RunPython.noop),
    ]
