# Generated by Django 5.2 on 2026-01-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_itemimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemimage",
            name="image_file",
            field=models.ImageField(blank=True, null=True, upload_to="item_images/"),
        ),
        migrations.AlterField(
            model_name="itemimage",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
